script:
  - "npm test"

language: node_js

node_js:
  - '4'
  - '6'

branches:
  only:
    - master
    - dev

matrix:
  fast_finish: true
  include:
    - node_js: "0.12"
      env: HARMONY=true
    - node_js: "4"
      env: COVERAGE=true
  allow_failures:
    - env: COVERAGE=true

sudo: false
